sudo: false
dist: trusty
branches:
  only:
    - master
    - /^greenkeeper-.*$/
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  chrome: "latest"
language: node_js
node_js:
  - "8"
rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:travis
after_success:
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov/lcov.info
  - ./cc-test-reporter upload-coverage
  - npm run travis-deploy-once "npm run semantic-release"
