sudo: required
dist: trusty
language: node_js
notifications:
  email: false
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "6"
before_install:
  - npm update -g
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g codeclimate-test-reporter
script:
  - npm test -- karma.conf.travis.js
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
